### ISSUE TITLE
batch_insert causes SEGV

### ISSUE THREAD

**Issue by zhanpon** [zhanpon/ngtpy#4]
## Description

```
$ python --version
Python 3.9.9

$ python -m pip freeze
ngtpy==0.1.0
numpy==1.22.3

$ cat insert.py
import tempfile
import ngtpy

with tempfile.TemporaryDirectory() as path:
    print("Creating index")
    ngtpy.create(path, 2)
    index = ngtpy.Index(path)

    print("Inserting vectors")
    index.insert([0, 1])
    index.insert([1, 0])
    print("Exiting")

$ python insert.py
Creating index
Inserting vectors
Exiting

$ cat batch_insert.py
import tempfile
import ngtpy

with tempfile.TemporaryDirectory() as path:
    print("Creating index")
    ngtpy.create(path, 2)
    index = ngtpy.Index(path)

    print("Inserting vectors")
    index.batch_insert([[0, 1], [1, 0]])
    print("Exiting")

$ python batch_insert.py
Creating index
Inserting vectors
Exiting
Segmentation fault (core dumped)
```

## Backtrace

```
$ coredumpctl gdb -1
           PID: 2347 (python)
           UID: 1000 (zhanpon)
           GID: 1000 (zhanpon)
        Signal: 11 (SEGV)
     Timestamp: Fri 2022-03-11 07:46:27 JST (47s ago)
  Command Line: python batch_insert.py
    Executable: /usr/bin/python3.9
 Control Group: /user.slice/user-1000.slice/session-1.scope
          Unit: session-1.scope
         Slice: user-1000.slice
       Session: 1
     Owner UID: 1000 (zhanpon)
       Boot ID: de2aabc080cb4fe5b22a95f99237e2db
    Machine ID: 575f560caf7544aca4d2c797752e6d71
      Hostname: shogun
       Storage: /var/lib/systemd/coredump/core.python.1000.de2aabc080cb4fe5b22a95f99237e2db.2347.1646952387000000.zst (present)
     Disk Size: 3.0M
       Message: Process 2347 (python) of user 1000 dumped core.

GNU gdb (Gentoo 11.2 vanilla) 11.2
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://bugs.gentoo.org/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/python3.9...
(No debugging symbols found in /usr/bin/python3.9)

warning: core file may not match specified executable file.
[New LWP 2347]
[New LWP 2349]
[New LWP 2348]
[New LWP 2350]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `python batch_insert.py'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007efcd2917e8a in free () from /lib64/libc.so.6
[Current thread is 1 (Thread 0x7efcd272f740 (LWP 2347))]
(gdb) bt
#0  0x00007efcd2917e8a in free () from /lib64/libc.so.6
#1  0x00007efcd21384a4 in ?? ()
   from /home/zhanpon/work/python/ngtpy/venv/lib/python3.9/site-packages/ngtpy/_ngtpy.cpython-39-x86_64-linux-gnu.so
#2  0x00007efcd20df2f6 in ?? ()
   from /home/zhanpon/work/python/ngtpy/venv/lib/python3.9/site-packages/ngtpy/_ngtpy.cpython-39-x86_64-linux-gnu.so
#3  0x00007efcd20f233b in ?? ()
   from /home/zhanpon/work/python/ngtpy/venv/lib/python3.9/site-packages/ngtpy/_ngtpy.cpython-39-x86_64-linux-gnu.so
#4  0x00007efcd211cc52 in ?? ()
   from /home/zhanpon/work/python/ngtpy/venv/lib/python3.9/site-packages/ngtpy/_ngtpy.cpython-39-x86_64-linux-gnu.so
#5  0x00007efcd21141a7 in ?? ()
   from /home/zhanpon/work/python/ngtpy/venv/lib/python3.9/site-packages/ngtpy/_ngtpy.cpython-39-x86_64-linux-gnu.so
#6  0x00007efcd20ff6eb in ?? ()
   from /home/zhanpon/work/python/ngtpy/venv/lib/python3.9/site-packages/ngtpy/_ngtpy.cpython-39-x86_64-linux-gnu.so
#7  0x00007efcd2b2fcb5 in ?? () from /usr/lib64/libpython3.9.so.1.0
#8  0x00007efcd2b30540 in ?? () from /usr/lib64/libpython3.9.so.1.0
#9  0x00007efcd2b3f1b5 in ?? () from /usr/lib64/libpython3.9.so.1.0
#10 0x00007efcd2b32915 in ?? () from /usr/lib64/libpython3.9.so.1.0
#11 0x00007efcd2bea6d0 in ?? () from /usr/lib64/libpython3.9.so.1.0
#12 0x00007efcd2c008e8 in Py_FinalizeEx () from /usr/lib64/libpython3.9.so.1.0
#13 0x00007efcd2c21834 in Py_RunMain () from /usr/lib64/libpython3.9.so.1.0
#14 0x00007efcd2c21f8a in Py_BytesMain () from /usr/lib64/libpython3.9.so.1.0
#15 0x00007efcd28b580d in __libc_start_main () from /lib64/libc.so.6
#16 0x00005565cc70908a in _start ()
```

**Comment by masajiro** [comment]
It might be caused by the difference between the build parameters of NGT and ngtpy.
